package UI.Recepcionista;
//Importamos las clases y las utilidades que usaremos en la actulizacion del usuario

import javax.swing.WindowConstants;
import Class.ConectorDB;
import java.sql.*;

/**
 *
 * @author jara
 */
public class ControlPaquetes extends javax.swing.JFrame {
    
//Atributo que declaramos global para poder ser usado en los distintos metodos    
    Connection cn = ConectorDB.conexion();
    /**
     * Constructor
     */
    public ControlPaquetes() {
        initComponents();
        setSize(700, 500);
        setResizable(false);
        setTitle("Control de Paquetes");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDPaquete = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jLabel1.setText("Introduzca el ID del Paquete:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 100, 330, 40);

        txtIDPaquete.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        txtIDPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPaqueteActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDPaquete);
        txtIDPaquete.setBounds(40, 150, 330, 50);

        txtUbicacion.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jPanel1.add(txtUbicacion);
        txtUbicacion.setBounds(160, 310, 330, 50);

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jLabel2.setText("El paquete se encuentra:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 250, 320, 40);

        jButton1.setBackground(new java.awt.Color(121, 221, 237));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 150, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPaqueteActionPerformed
//Este metodo permite la busque del Paque mediante su id y regresa la localizacion del paquete
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ubicacion, id;
        id = txtIDPaquete.getText().trim();
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT localizacion FROM Paquete WHERE id_paquete='"+id+"'");
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                ubicacion = rs.getString("localizacion");                
                txtUbicacion.setText(ubicacion);
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener la ubicacion del paquete "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIDPaquete;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
