package UI;
import java.sql.*;
import Class.ConectorDB;
import javax.swing.WindowConstants;

/**
 *
 * @author jara
 */
public class Administrador extends javax.swing.JFrame {
    String user;
    String nombre_usuario;
    public static int sesion_usuario;
    
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setSize(800, 650);
        setResizable(false);
        setTitle("Administrador");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
        sesion_usuario =1;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        try {
            Connection cn = ConectorDB.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT nombre_usuario FROM Usuario WHERE username= '"+ user +"'");
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                nombre_usuario =rs.getString("nombre_usuario");
                jLblUsu.setText("Bienvenido: " +nombre_usuario);
            }
        } catch (SQLException e) {
            System.err.println("Error en la conexion de DB con Administrador");
            
        }  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblUsu = new javax.swing.JLabel();
        btnRegistrarU = new javax.swing.JButton();
        btnAdministrarU = new javax.swing.JButton();
        btnPuntosControl = new javax.swing.JButton();
        btnAdminOpe = new javax.swing.JButton();
        btnAdminRecep = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnColas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 168, 207));
        jPanel1.setLayout(null);

        jLblUsu.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jPanel1.add(jLblUsu);
        jLblUsu.setBounds(170, 20, 481, 28);

        btnRegistrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addUser.png"))); // NOI18N
        btnRegistrarU.setBorder(null);
        btnRegistrarU.setContentAreaFilled(false);
        btnRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarU);
        btnRegistrarU.setBounds(50, 100, 120, 100);

        btnAdministrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informationuser.png"))); // NOI18N
        btnAdministrarU.setBorder(null);
        btnAdministrarU.setContentAreaFilled(false);
        btnAdministrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarUActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrarU);
        btnAdministrarU.setBounds(240, 100, 120, 100);

        btnPuntosControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkpoint-3-461915.png"))); // NOI18N
        btnPuntosControl.setBorder(null);
        btnPuntosControl.setContentAreaFilled(false);
        btnPuntosControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntosControlActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuntosControl);
        btnPuntosControl.setBounds(50, 300, 120, 100);

        btnAdminOpe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tecnico.png"))); // NOI18N
        btnAdminOpe.setBorder(null);
        btnAdminOpe.setContentAreaFilled(false);
        btnAdminOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminOpeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminOpe);
        btnAdminOpe.setBounds(430, 100, 120, 100);

        btnAdminRecep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Receptionist.png"))); // NOI18N
        btnAdminRecep.setBorder(null);
        btnAdminRecep.setContentAreaFilled(false);
        btnAdminRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminRecepActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminRecep);
        btnAdminRecep.setBounds(620, 100, 120, 100);

        btnRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/route.png"))); // NOI18N
        btnRutas.setBorder(null);
        btnRutas.setContentAreaFilled(false);
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRutas);
        btnRutas.setBounds(240, 300, 120, 100);

        btnColas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paquetes-png-2-300x200.png"))); // NOI18N
        btnColas.setBorder(null);
        btnColas.setContentAreaFilled(false);
        btnColas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColasActionPerformed(evt);
            }
        });
        jPanel1.add(btnColas);
        btnColas.setBounds(430, 300, 120, 100);

        jLabel1.setText("Registrar Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 210, 150, 15);

        jLabel2.setText("Gestionar Usuarios");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 210, 120, 15);

        jLabel3.setText("Gestionar Operador");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 210, 130, 15);

        jLabel4.setText("Gestionar Recepcionista");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 210, 150, 15);

        jLabel5.setText("<html>Gestionar Puntos de Control<html>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 410, 120, 60);

        jLabel6.setText("Rutas de Paquetes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 410, 120, 15);

        jLabel7.setText("Cola de Paquetes");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 410, 120, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminRecepActionPerformed
     Recepcionista rp = new Recepcionista();
     rp.setVisible(true);
    }//GEN-LAST:event_btnAdminRecepActionPerformed

    private void btnRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUActionPerformed
        jFRegistrarUsuario ru = new jFRegistrarUsuario();
        ru.setVisible(true);
    }//GEN-LAST:event_btnRegistrarUActionPerformed

    private void btnColasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColasActionPerformed
       jFColas colas = new jFColas();
       colas.setVisible(true);
    }//GEN-LAST:event_btnColasActionPerformed

    private void btnAdministrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUActionPerformed
       jFGestionarUsuario gu = new jFGestionarUsuario();
       gu.setVisible(true);        
    }//GEN-LAST:event_btnAdministrarUActionPerformed

    private void btnPuntosControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntosControlActionPerformed
        jFCheckpoints cp = new jFCheckpoints();
        cp.setVisible(true);
    }//GEN-LAST:event_btnPuntosControlActionPerformed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        jFRutas r = new jFRutas();
        r.setVisible(true);
    }//GEN-LAST:event_btnRutasActionPerformed

    private void btnAdminOpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminOpeActionPerformed
        Operador op = new Operador();
        op.setVisible(true);
    }//GEN-LAST:event_btnAdminOpeActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminOpe;
    private javax.swing.JButton btnAdminRecep;
    private javax.swing.JButton btnAdministrarU;
    private javax.swing.JButton btnColas;
    private javax.swing.JButton btnPuntosControl;
    private javax.swing.JButton btnRegistrarU;
    private javax.swing.JButton btnRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblUsu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
