package UI;

import Class.ConectorDB;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author jara
 */
public class FromPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FromPrincipal
     */
    public static String user = "";
    String pass = "";

    public FromPrincipal() {
        initComponents();
        setSize(700, 650);
        setResizable(false);
        setTitle("Servicio Express de Paqueteria iVoy");
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFNomUser = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 350, 320);

        jLabel2.setText("Ingrese nombre del Usuario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 360, 170, 30);

        btn_Ingresar.setText("INGRESAR");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ingresar);
        btn_Ingresar.setBounds(530, 400, 120, 30);

        jLabel4.setText("Ingrese su Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 360, 170, 30);
        jPanel1.add(jTFNomUser);
        jTFNomUser.setBounds(20, 400, 230, 32);

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField);
        jPasswordField.setBounds(280, 400, 180, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        user = jTFNomUser.getText().trim();
        pass = jPasswordField.getText().trim();
        if (!user.equals("") || !pass.equals("")) {
        try {
                Connection cn = ConectorDB.conexion();
                PreparedStatement ps = cn.prepareStatement("SELECT tipo_nivel, estado FROM Usuario WHERE username = '" + user
                        + "' and password ='" + pass + "'");
                ResultSet rS = ps.executeQuery();
                if (rS.next()) {
                    String tipo_nivel = rS.getString("tipo_nivel");
                    String estado = rS.getString("estado");
                    if (tipo_nivel.equalsIgnoreCase("Administrador") && estado.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Administrador().setVisible(true);
                    } else if (tipo_nivel.equalsIgnoreCase("Operador") && estado.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Operador().setVisible(true);
                    } else if (tipo_nivel.equalsIgnoreCase("Recepcionista") && estado.equalsIgnoreCase("Activo")) {
                        dispose();
                        new Recepcionista().setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Datos ingresados incorrectos!");
                    jTFNomUser.setText("");
                    jPasswordField.setText("");
                }
            } catch (SQLException ex) {
                System.err.println("Error en el boton acceder" +ex);
                JOptionPane.showMessageDialog(null, "Error al ingresar el usuario!");                     
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar los campos para ingresar!");
            jTFNomUser.setText("");
            jPasswordField.setText("");
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTFNomUser;
    // End of variables declaration//GEN-END:variables
}
