package UI;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import Class.ConectorDB;
import java.sql.Connection;

/**
 *
 * @author jara
 */
public class jFActualizarRuta extends javax.swing.JFrame {

    Connection cn = ConectorDB.conexion();
    int cmb_estado;
    String cmb_Estado;

    /**
     * Creates new form jFActualizarRuta
     */
    public jFActualizarRuta() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Actualizar Ruta");
        setLocationRelativeTo(null);
        jLabel1.setText("Actualizar la Ruta: " + jFGestionarRuta.nombreRuta);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        infoRuta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreR = new javax.swing.JTextField();
        txtDestinoR = new javax.swing.JTextField();
        cmbEstadoR = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIDRuta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 580, 40);

        jLabel2.setText("Nombre de la Ruta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 140, 140, 15);

        jLabel3.setText("Estado de la Ruta:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 330, 140, 15);

        jLabel4.setText("Destino de la Ruta:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 240, 140, 15);
        jPanel1.add(txtNombreR);
        txtNombreR.setBounds(50, 160, 280, 32);
        jPanel1.add(txtDestinoR);
        txtDestinoR.setBounds(50, 260, 280, 32);

        cmbEstadoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva" }));
        cmbEstadoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoRActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEstadoR);
        cmbEstadoR.setBounds(50, 350, 160, 32);

        jButton1.setText("Actualizar Ruta");
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 330, 160, 80);

        jLabel5.setText("ID de la Ruta");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 140, 110, 15);

        txtIDRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDRutaActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDRuta);
        txtIDRuta.setBounds(420, 160, 90, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoRActionPerformed

    private void txtIDRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDRutaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEstadoR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDestinoR;
    private javax.swing.JTextField txtIDRuta;
    private javax.swing.JTextField txtNombreR;
    // End of variables declaration//GEN-END:variables

    public void infoRuta() {
        try {
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT * FROM Rutas WHERE id_rutas ='" + jFGestionarRuta.actualizarRuta + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtNombreR.setText(rs.getString("nombre_ruta"));
                txtDestinoR.setText(rs.getString("destino"));
                txtIDRuta.setText(rs.getString("id_rutas"));
                cmbEstadoR.setSelectedItem(rs.getString("estado_ruta"));
            }
        } catch (SQLException e) {
            System.err.println("Error al cargar ruta" + e);
            JOptionPane.showMessageDialog(null, "Error al cargar ruta!");
        }
    }

    public void combo() {
        cmb_estado = cmbEstadoR.getSelectedIndex() + 1;
        if (cmb_estado == 1) {
            cmb_Estado = "Activo";
        } else if (cmb_estado == 2) {
            cmb_Estado = "Inactivo";
        }
    }
}
