package UI;
import java.sql.*;
import Class.ConectorDB;
/**
 *
 * @author jara
 */
public class jFCobrar extends javax.swing.JFrame {
    String user;
    /**
     * Creates new form jFCobrar
     */
    public jFCobrar() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Pagar Paquete");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrarPago = new javax.swing.JButton();
        txtPIDCliente = new javax.swing.JTextField();
        txtPIDPaquete = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtTotalPago = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 3, 24)); // NOI18N
        jLabel1.setText("Cobro de Paquete");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 260, 40);

        jLabel2.setText("Ingrese ID del Cliente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 190, 15);

        jLabel3.setText("Ingrese ID del Paquete");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 190, 15);

        jLabel4.setText("Fecha de Pago");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 80, 88, 15);

        jLabel5.setText("Total a Pagar:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 260, 160, 20);

        jLabel6.setText("Efectivo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 160, 15);

        jLabel7.setText("Cambio:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 340, 150, 15);

        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPago);
        btnRegistrarPago.setBounds(240, 390, 120, 70);
        jPanel1.add(txtPIDCliente);
        txtPIDCliente.setBounds(20, 100, 190, 32);
        jPanel1.add(txtPIDPaquete);
        txtPIDPaquete.setBounds(20, 190, 190, 32);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(360, 100, 230, 32);
        jPanel1.add(txtTotalPago);
        txtTotalPago.setBounds(350, 260, 260, 32);
        jPanel1.add(txtEfectivo);
        txtEfectivo.setBounds(350, 300, 260, 32);
        jPanel1.add(txtCambio);
        txtCambio.setBounds(350, 340, 260, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPago;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtPIDCliente;
    private javax.swing.JTextField txtPIDPaquete;
    private javax.swing.JTextField txtTotalPago;
    // End of variables declaration//GEN-END:variables
}
