package UI;
import java.sql.*;
import Class.ConectorDB;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jara
 */
public class jFGestionarCliente extends javax.swing.JFrame {
    
    String user;
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form jFGestionarCliente
     */
    public jFGestionarCliente() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Gestionar Cliente");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = ConectorDB.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT id_cliente, nombre_cliente, can_paquetes FROM Clientes");
            ResultSet rs = ps.executeQuery();
            jTableClientes = new JTable(model);
            jScrollPane1.setViewportView(jTableClientes);
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Cantidad de Paquetes");
            
            while (rs.next()) {
                Object[] ob = new Object[3];
                for (int i = 0; i < ob.length; i++) {
                    ob[i] = rs.getObject(i + 1);
                }
                model.addRow(ob);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al rellenar la tabla" +e);
            JOptionPane.showMessageDialog(null, "Error en la conexion DB con la Tabla");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nimbus Sans Narrow", 3, 24)); // NOI18N
        jLabel1.setText("Informacion de los Clientes");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 330, 40);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Paquetes"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 70, 540, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
