package UI;
import java.sql.*;
import Class.ConectorDB;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jara
 */
public class jFGestionarUsuario extends javax.swing.JFrame {

    String user;
    public static String actualizarU = "";
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form jFGestionarUsuario
     */
    public jFGestionarUsuario() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Gestionar Usuarios");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = ConectorDB.conexion();
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT id_usuario, nombre_usuario, username, password, tipo_nivel, estado FROM Usuario");
            ResultSet rs = ps.executeQuery();
            jTableUsuarios = new JTable(model);
            jScrollPane1.setViewportView(jTableUsuarios);
            model.addColumn("ID_Usuario");
            model.addColumn("Nombre");
            model.addColumn("Username");
            model.addColumn("PassWord");
            model.addColumn("Nivel");
            model.addColumn("Estado");
            while (rs.next()) {
                Object[] ob = new Object[6];
                for (int i = 0; i < ob.length; i++) {
                    ob[i] = rs.getObject(i + 1);
                }
                model.addRow(ob);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al rellenar la tabla");
            JOptionPane.showMessageDialog(null, "Error en la conexion DB con la Tabla");
        }
        
        jTableUsuarios.addMouseListener(new MouseAdapter() {
           @Override
           public void mouseClicked(MouseEvent e){
               int fila_point = jTableUsuarios.rowAtPoint(e.getPoint());
               int columna_point = 2;
               if(fila_point>-1){
                   actualizarU= (String)model.getValueAt(fila_point, columna_point);
                   jFActualizarU go= new jFActualizarU();
                   go.setVisible(true);
               }
           }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Source Code Variable", 3, 24)); // NOI18N
        jLabel1.setText("Informacion de los Usuarios:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 460, 40);

        jScrollPane1.setBackground(java.awt.Color.lightGray);
        jScrollPane1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Usuario", "Nombre", "Username", "PassWord", "Nivel", "Estado"
            }
        ));
        jTableUsuarios.setEnabled(false);
        jScrollPane1.setViewportView(jTableUsuarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 610, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
