package UI;

import java.sql.*;
import Class.ConectorDB;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import UI.jFRegistrarCliente;
import java.util.ArrayList;

/**
 *
 * @author jara
 */
public class jFRegistrarPaquete extends javax.swing.JFrame {

    String user;
    Connection cn = ConectorDB.conexion();
    String nitCliente;
    String cmb_Destino;

    /**
     * Creates new form jFRegistrarPaquete
     */
    public jFRegistrarPaquete() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Registrar Nuevo Paquete");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        aggDestino();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        cmbPrioridad = new javax.swing.JComboBox<>();
        btnRegistrarPaquete = new javax.swing.JButton();
        jDFecha = new com.toedter.calendar.JDateChooser();
        cmbDestino = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Datos de Paquete");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 20, 240, 40);

        jLabel2.setText("Ingrese el NIT del Cliente");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 90, 170, 15);

        jLabel4.setText("Ingrese el Peso del Paquete(Libras)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 190, 230, 15);

        jLabel5.setText("Fecha y Hora de Ingreso");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(350, 90, 170, 15);

        jLabel6.setText("Prioridad del paquete");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 380, 150, 15);

        jLabel7.setText("Seleccione Destino del Paquete");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 270, 200, 15);
        jPanel2.add(txtIDCliente);
        txtIDCliente.setBounds(30, 110, 220, 32);
        jPanel2.add(txtPeso);
        txtPeso.setBounds(30, 210, 220, 32);

        cmbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", " " }));
        jPanel2.add(cmbPrioridad);
        cmbPrioridad.setBounds(30, 400, 70, 32);

        btnRegistrarPaquete.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnRegistrarPaquete.setText("Registrar Paquete");
        btnRegistrarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPaqueteActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarPaquete);
        btnRegistrarPaquete.setBounds(380, 290, 160, 100);

        jDFecha.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jPanel2.add(jDFecha);
        jDFecha.setBounds(350, 120, 230, 32);

        jPanel2.add(cmbDestino);
        cmbDestino.setBounds(30, 290, 280, 32);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPaqueteActionPerformed
        aggPaquete();
    }//GEN-LAST:event_btnRegistrarPaqueteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPaquete;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbPrioridad;
    private com.toedter.calendar.JDateChooser jDFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
    public void clear() {

        txtIDCliente.setText("");
        txtPeso.setText("");
        cmbDestino.setSelectedIndex(0);
        cmbPrioridad.setSelectedIndex(0);

    }

    public void aggPaquete() {
        int prioridad_cmb, validacion = 0;
        float costo = 0;
        boolean prioridad_boolean = true;
        String peso, estado_paquete;
        String fecha = ((JTextField) jDFecha.getDateEditor().getUiComponent()).getText();
        int cantidad = 1;

        nitCliente = txtIDCliente.getText().trim();
        peso = txtPeso.getText().trim();
        prioridad_cmb = cmbPrioridad.getSelectedIndex() + 1;
        cmb_Destino = cmbDestino.getSelectedItem().toString();
        estado_paquete = "No entregado";
        costo = 0;

        if (nitCliente.equals("")) {
            txtIDCliente.setBackground(Color.red);
            validacion++;
        }
        if (peso.equals("")) {
            txtPeso.setBackground(Color.red);
            validacion++;
        }
        if (prioridad_cmb == 1) {
            prioridad_boolean = true;
        } else if (prioridad_cmb == 2) {
            prioridad_boolean = false;
        }

        compareNIT();
        if (validacion == 0) {
            try {
                PreparedStatement ps1 = cn.prepareStatement("INSERT INTO Paquete VALUES(?,?,?,?,?,?,?,?)");
                ps1.setInt(1, 0);
                ps1.setString(2, nitCliente);
                ps1.setString(3, peso);
                ps1.setString(4, cmb_Destino);
                ps1.setString(5, fecha);
                ps1.setBoolean(6, prioridad_boolean);
                ps1.setString(7, estado_paquete);
                ps1.setFloat(8, costo);
                ps1.executeUpdate();
                cn.close();
                clear();
                txtIDCliente.setBackground(Color.green);
                txtPeso.setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Paquete ingresado exitosamente!");
                this.dispose();
            } catch (SQLException e) {
                System.err.println("Error al registrar paquete." + e);
                JOptionPane.showMessageDialog(null, "El NIT ingresado no existe!! \n Cree el cliente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos incompletos!! \n Ingrese todos los datos.");

        }

    }

    public void compareNIT() {
        try {
            PreparedStatement ps1 = cn.prepareStatement("SELECT nit_cliente FROM Clientes WHERE nit_cliente ='" + nitCliente + "'");
            ResultSet rs = ps1.executeQuery();
            if (rs.next()) {
            } else {
                jFRegistrarCliente rg = new jFRegistrarCliente();
                rg.setVisible(true);
            }
        } catch (SQLException e) {
            System.err.println("Error al crear cliente en paquete " + e);
        }
    }

    public void aggDestino() {
        ArrayList<String> list = new ArrayList<String>();

        try {
            PreparedStatement ps2 = cn.prepareStatement("SELECT destino FROM Rutas WHERE estado_ruta='Activo'");
            ResultSet rs2 = ps2.executeQuery();
            while (rs2.next()) {
                list.add(rs2.getString("destino"));
            }
            for (int i = 0; i < list.size(); i++) {
                cmbDestino.addItem(list.get(i));
            }
        } catch (SQLException e) {
            System.err.println("Error en el array " + e);
        }
    }
}
