package UI;
import Class.ConectorDB;
import java.sql.*;
import javax.swing.WindowConstants;
 
/**
 *
 * @author jara
 */
public class Recepcionista extends javax.swing.JFrame {
    String user, nombre_usuario;
    int sesion_usuario;
    /**
     * Creates new form Recepcionista
     */
    public Recepcionista() {
        initComponents();
        setSize(700, 500);
        setResizable(false);
        setTitle("Recepcionista");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
        sesion_usuario = Administrador.sesion_usuario;
        
        if (sesion_usuario==1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        
        try {
            Connection cn = ConectorDB.conexion();
            PreparedStatement ps =cn.prepareStatement(
                    "SELECT nombre_usuario FROM Usuario WHERE username = '"
            + user +"'");
        ResultSet rs = ps.executeQuery();
        if(rs.next()){
            nombre_usuario = rs.getString("nombre_usuario");
            jLabel6.setText("Usuario en uso: " +nombre_usuario); 
        }
        } catch (SQLException e) {
            System.err.println("Error en la conexion de DB con Recepcionista");
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarPa = new javax.swing.JButton();
        btnControlPa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGestionarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(650, 500));

        jPanel1.setBackground(new java.awt.Color(217, 125, 180));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel1.setLayout(null);

        btnRegistrarPa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pack.png"))); // NOI18N
        btnRegistrarPa.setBorder(null);
        btnRegistrarPa.setContentAreaFilled(false);
        btnRegistrarPa.setPreferredSize(new java.awt.Dimension(120, 100));
        btnRegistrarPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPa);
        btnRegistrarPa.setBounds(70, 100, 120, 100);

        btnControlPa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Control.png"))); // NOI18N
        btnControlPa.setBorder(null);
        btnControlPa.setContentAreaFilled(false);
        btnControlPa.setPreferredSize(new java.awt.Dimension(120, 100));
        btnControlPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlPaActionPerformed(evt);
            }
        });
        jPanel1.add(btnControlPa);
        btnControlPa.setBounds(490, 100, 120, 100);

        jLabel2.setText("Registrar Paquete");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 200, 120, 15);

        jLabel3.setText("Control de Paquetes");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 200, 160, 15);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 10, 440, 40);

        btnGestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informationuser.png"))); // NOI18N
        btnGestionarCliente.setBorder(null);
        btnGestionarCliente.setContentAreaFilled(false);
        btnGestionarCliente.setPreferredSize(new java.awt.Dimension(120, 100));
        btnGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionarCliente);
        btnGestionarCliente.setBounds(280, 100, 120, 100);

        jLabel5.setText("Gestionar Clientes");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 200, 120, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnControlPaActionPerformed

    private void btnRegistrarPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPaActionPerformed
        jFRegistrarPaquete rp = new jFRegistrarPaquete();
        rp.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPaActionPerformed

    private void btnGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClienteActionPerformed
        jFGestionarCliente gc = new jFGestionarCliente();
        gc.setVisible(true);
    }//GEN-LAST:event_btnGestionarClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControlPa;
    private javax.swing.JButton btnGestionarCliente;
    private javax.swing.JButton btnRegistrarPa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
