package UI.Administrador;
//Importamos las clases y herramientas que nos serviran en la estructuracion del codigo

import UI.Administrador.jFRutas;
import UI.Inicio.FromPrincipal;
import java.sql.*;
import Class.ConectorDB;
import javax.swing.WindowConstants;

/**
 *
 * @author jara
 */
public class Administrador extends javax.swing.JFrame {
//Atributos globales que usaremos en el desarrollo de los metedos    

    String user;
    String nombre_usuario;
    public static int sesion_usuario;
    Connection cn = ConectorDB.conexion();

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setSize(800, 650);
        setResizable(false);
        setTitle("Administrador");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
        sesion_usuario = 1;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblUsu = new javax.swing.JLabel();
        btnRegistrarU = new javax.swing.JButton();
        btnAdministrarU = new javax.swing.JButton();
        btnPuntosControl = new javax.swing.JButton();
        btnAdminOpe = new javax.swing.JButton();
        btnAdminRecep = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnColas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 168, 207));
        jPanel1.setLayout(null);

        jLblUsu.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jPanel1.add(jLblUsu);
        jLblUsu.setBounds(170, 20, 481, 28);

        btnRegistrarU.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnRegistrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addUser.png"))); // NOI18N
        btnRegistrarU.setText("Registrar Usuario");
        btnRegistrarU.setBorder(null);
        btnRegistrarU.setContentAreaFilled(false);
        btnRegistrarU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarU);
        btnRegistrarU.setBounds(30, 120, 150, 100);

        btnAdministrarU.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnAdministrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informationuser.png"))); // NOI18N
        btnAdministrarU.setText("Gestionar Usuario");
        btnAdministrarU.setBorder(null);
        btnAdministrarU.setContentAreaFilled(false);
        btnAdministrarU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrarU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarUActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrarU);
        btnAdministrarU.setBounds(230, 120, 150, 100);

        btnPuntosControl.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnPuntosControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkpoint-3-461915.png"))); // NOI18N
        btnPuntosControl.setText("Crear Punto Control");
        btnPuntosControl.setBorder(null);
        btnPuntosControl.setContentAreaFilled(false);
        btnPuntosControl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPuntosControl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPuntosControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntosControlActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuntosControl);
        btnPuntosControl.setBounds(20, 340, 170, 100);

        btnAdminOpe.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnAdminOpe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkpoint-3-461915.png"))); // NOI18N
        btnAdminOpe.setText("Gestionar Punto Control");
        btnAdminOpe.setBorder(null);
        btnAdminOpe.setContentAreaFilled(false);
        btnAdminOpe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminOpe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdminOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminOpeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminOpe);
        btnAdminOpe.setBounds(210, 340, 210, 100);

        btnAdminRecep.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnAdminRecep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/route.png"))); // NOI18N
        btnAdminRecep.setText("Gestionar Ruta");
        btnAdminRecep.setBorder(null);
        btnAdminRecep.setContentAreaFilled(false);
        btnAdminRecep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminRecep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdminRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminRecepActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminRecep);
        btnAdminRecep.setBounds(620, 120, 120, 100);

        btnRutas.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/route.png"))); // NOI18N
        btnRutas.setText("Crear Ruta");
        btnRutas.setBorder(null);
        btnRutas.setContentAreaFilled(false);
        btnRutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRutas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRutas);
        btnRutas.setBounds(420, 110, 150, 120);

        btnColas.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnColas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paquetes-png-2-300x200.png"))); // NOI18N
        btnColas.setText("Cola de Paquetes");
        btnColas.setBorder(null);
        btnColas.setContentAreaFilled(false);
        btnColas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColasActionPerformed(evt);
            }
        });
        jPanel1.add(btnColas);
        btnColas.setBounds(430, 340, 160, 100);

        btnSalir.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(630, 500, 120, 100);

        btnReportes.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grafica.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setPreferredSize(new java.awt.Dimension(120, 100));
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes);
        btnReportes.setBounds(630, 340, 120, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Este boton tiene el evento de dirigirnos a Gestionar Ruta
    private void btnAdminRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminRecepActionPerformed
        jFGestionarRuta gr = new jFGestionarRuta();
        gr.setVisible(true);
    }//GEN-LAST:event_btnAdminRecepActionPerformed
//Este boton tiene el evento de dirigirnos a Crear Usuario
    private void btnRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUActionPerformed
        jFRegistrarUsuario ru = new jFRegistrarUsuario();
        ru.setVisible(true);
    }//GEN-LAST:event_btnRegistrarUActionPerformed
//Este boton tiene el evento de dirigirnos a Crear Colas
    private void btnColasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColasActionPerformed
        jFColas colas = new jFColas();
        colas.setVisible(true);
    }//GEN-LAST:event_btnColasActionPerformed
//Este boton tiene el evento de dirigirnos a Administrar Usuarios
    private void btnAdministrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUActionPerformed
        jFGestionarUsuario gu = new jFGestionarUsuario();
        gu.setVisible(true);
    }//GEN-LAST:event_btnAdministrarUActionPerformed
//Este boton tiene el evento de dirigirnos a Crear Puntos de Control
    private void btnPuntosControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntosControlActionPerformed
        jFCheckpoints cp = new jFCheckpoints();
        cp.setVisible(true);
    }//GEN-LAST:event_btnPuntosControlActionPerformed
//Este boton tiene el evento de dirigirnos a Crear Ruta
    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        jFRutas r = new jFRutas();
        r.setVisible(true);
    }//GEN-LAST:event_btnRutasActionPerformed
//Este boton tiene el evento de dirigirnos a Gestionar PC
    private void btnAdminOpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminOpeActionPerformed
        jFGestionarPuntoControl gpc = new jFGestionarPuntoControl();
        gpc.setVisible(true);
    }//GEN-LAST:event_btnAdminOpeActionPerformed
//Este boton tiene el evento de dirigirnos al FROM Principal
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        FromPrincipal fpn = new FromPrincipal();
        fpn.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed
//Este boton tiene el evento de dirigirnos a los Reportes
    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        jFReportes rps = new jFReportes();
        rps.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminOpe;
    private javax.swing.JButton btnAdminRecep;
    private javax.swing.JButton btnAdministrarU;
    private javax.swing.JButton btnColas;
    private javax.swing.JButton btnPuntosControl;
    private javax.swing.JButton btnRegistrarU;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnRutas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLblUsu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
//Metodo que permite ver quien ingreso a la interfaz Administrador
    public void login() {
        try {
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT nombre_usuario FROM Usuario WHERE username= '" + user + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre_usuario");
                jLblUsu.setText("Bienvenido: " + nombre_usuario);
            }
        } catch (SQLException e) {
            System.err.println("Error en la conexion de DB con Administrador");
        }
    }
}
