package UI.Administrador;
import UI.Inicio.FromPrincipal;
import javax.swing.WindowConstants;
import java.sql.*;
import Class.ConectorDB;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jara
 */
public class jFActualizarU extends javax.swing.JFrame {
    String user="";
    String user_update="";
    int ID;
    
    
    /**
     * Creates new form jFGestionarOpe
     */
    public jFActualizarU() {
        initComponents();
        setTitle("Actualizar Usuario");
        setSize(650, 500);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        user = FromPrincipal.user;
        user_update = jFGestionarUsuario.actualizarU;
        jLabel1.setText("Imformacion del usuario: " +user_update);
        
        try {
            Connection cn = ConectorDB.conexion();
            PreparedStatement ps = cn.prepareStatement(
            "SELECT * FROM Usuario WHERE username= '" +user_update+"'");
            ResultSet rs= ps.executeQuery();
            if(rs.next()){
            ID = rs.getInt("id_usuario");
            txtActualizarID.setText(rs.getString("id_usuario"));
            txtActualizarNom.setText(rs.getString("nombre_usuario"));
            txtActualizarUser.setText(rs.getString("username")); 
            txtActualizarPass.setText(rs.getString("password"));
            cmbActualizarNi.setSelectedItem(rs.getString("tipo_nivel"));
            cmbActualizarE.setSelectedItem(rs.getString("estado"));
            
            }
            cn.close();
        } catch (SQLException e) {
        System.err.println("Error al cargar usuario" + e);
        JOptionPane.showMessageDialog(null, "Error al cargar usuario!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnActualizarU = new javax.swing.JButton();
        cmbActualizarNi = new javax.swing.JComboBox<>();
        txtActualizarID = new javax.swing.JTextField();
        txtActualizarNom = new javax.swing.JTextField();
        txtActualizarUser = new javax.swing.JTextField();
        txtActualizarPass = new javax.swing.JTextField();
        cmbActualizarE = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Source Code Pro Semibold", 3, 24)); // NOI18N
        jLabel1.setText("Informacion del Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 610, 40);

        lblID.setText("ID Usuario");
        jPanel1.add(lblID);
        lblID.setBounds(30, 90, 90, 15);

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre);
        lblNombre.setBounds(30, 180, 80, 15);

        lblUsername.setText("Username");
        jPanel1.add(lblUsername);
        lblUsername.setBounds(30, 270, 61, 15);

        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(30, 360, 110, 15);

        lblNivel.setText("Nivel del Usuario");
        jPanel1.add(lblNivel);
        lblNivel.setBounds(390, 90, 180, 15);

        lblEstado.setText("Estado del Usuario");
        jPanel1.add(lblEstado);
        lblEstado.setBounds(390, 210, 180, 15);

        btnActualizarU.setText("Actualizar Datos");
        btnActualizarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarU);
        btnActualizarU.setBounds(410, 350, 150, 60);

        cmbActualizarNi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Recepcionista", " " }));
        jPanel1.add(cmbActualizarNi);
        cmbActualizarNi.setBounds(390, 110, 139, 32);

        txtActualizarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtActualizarID);
        txtActualizarID.setBounds(30, 110, 290, 32);

        txtActualizarNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtActualizarNom);
        txtActualizarNom.setBounds(30, 200, 290, 32);

        txtActualizarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtActualizarUser);
        txtActualizarUser.setBounds(30, 290, 290, 32);
        jPanel1.add(txtActualizarPass);
        txtActualizarPass.setBounds(30, 380, 290, 32);

        cmbActualizarE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));
        jPanel1.add(cmbActualizarE);
        cmbActualizarE.setBounds(390, 230, 102, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtActualizarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActualizarUserActionPerformed

    private void txtActualizarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActualizarIDActionPerformed

    private void txtActualizarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActualizarNomActionPerformed

    private void btnActualizarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUActionPerformed
        int permisos_cmb, estatus_cmb, validacion=0;
        String nombre, username, pass, permisos_string="", estado_string="";
        
        nombre = txtActualizarNom.getText().trim();
        username = txtActualizarUser.getText().trim();
        pass = txtActualizarPass.getText().trim();
        permisos_cmb= cmbActualizarNi.getSelectedIndex() +1;
        estatus_cmb= cmbActualizarE.getSelectedIndex()+1;
        
        if(nombre.equals("")){
        txtActualizarNom.setBackground(Color.red);
        validacion++;
        }
        if(username.equals("")){
        txtActualizarUser.setBackground(Color.red);
        validacion++;
        }
        if(pass.equals("")){
        txtActualizarPass.setBackground(Color.red);
        validacion++;
        }
        if(validacion==0){
            if(permisos_cmb==1){
            permisos_string= "Administrador";
            }else if(permisos_cmb==2){
            permisos_string= "Operador";
            }else if(permisos_cmb==3){
            permisos_string= "Recepcionista";
            }
            
            if(estatus_cmb==1){
                estado_string = "Activo";
            }else if(estatus_cmb==2){
                estado_string = "Inactivo";
            }
            try {
                Connection cn = ConectorDB.conexion();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT username FROM Usuario WHERE username='" +username+"'and not id_usuario = '" + ID + "'");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    txtActualizarUser.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Nombre de usuario ya existente");                   
                    cn.close();
                } else {
                Connection cn1 = ConectorDB.conexion();
                PreparedStatement ps1 = cn1.prepareStatement(
                        "UPDATE Usuario SET nombre_usuario=?, username=?, password=?, tipo_nivel=?, estado=? " 
                                + "WHERE id_usuario= '" + ID + "'");
                ps1.setString(1, nombre);
                ps1.setString(2, username);
                ps1.setString(3, pass);
                ps1.setString(4, permisos_string);
                ps1.setString(5, estado_string);
                ps1.executeUpdate();
                cn1.close();
                JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente!");
                }
            } catch (SQLException e) {
            System.err.println("Error al actualizar" + e);
            JOptionPane.showMessageDialog(null, "Error al actualizar usuario!");
            }
 
        }else{
            JOptionPane.showMessageDialog(null,"Debe de rellenar todos lo campos de informacion!");
        }
        
        
    }//GEN-LAST:event_btnActualizarUActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarU;
    private javax.swing.JComboBox<String> cmbActualizarE;
    private javax.swing.JComboBox<String> cmbActualizarNi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtActualizarID;
    private javax.swing.JTextField txtActualizarNom;
    private javax.swing.JTextField txtActualizarPass;
    private javax.swing.JTextField txtActualizarUser;
    // End of variables declaration//GEN-END:variables
}
