package UI.Administrador;
import java.sql.*;
import Class.ConectorDB;
import javax.swing.WindowConstants;
/**
 *
 * @author jara
 */
public class jFReportes extends javax.swing.JFrame {

    /**
     * Creates new form jFReportes
     */
    
    public jFReportes() {
        initComponents();
        setSize(800, 300);
        setResizable(false);
        setTitle("Reportes");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
     
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jLabel1.setText("Seleccione el Reporte que desea ver:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 420, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquetes en Ruta", "Ganancias", "Clientes", "Popularidad" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 40, 370, 32);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 40, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        combo();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public void combo(){
    String cmb=jComboBox1.getSelectedItem().toString();
    if(cmb=="Paquetes en Ruta"){
    Reporte1 r1= new Reporte1();
    r1.setVisible(true);
    }
    if(cmb=="Ganancias"){
    Reporte2 r2= new Reporte2();
    r2.setVisible(true);
    }
    }
}
