package UI.Administrador;

import UI.Inicio.FromPrincipal;
import java.sql.*;
import Class.ConectorDB;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author jara
 */
public class jFRutas extends javax.swing.JFrame {

    String user;
    Connection cn = ConectorDB.conexion();

    /**
     * Creates new form jFRutas
     */
    public jFRutas() {
        initComponents();
        setSize(700, 500);
        setResizable(false);
        setTitle("Crear Rutas");
        setLocationRelativeTo(null);
        user = FromPrincipal.user;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        txtNombreR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbEstadoRuta = new javax.swing.JComboBox<>();
        btnCrearRuta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioDestino = new javax.swing.JTextField();
        txtPrecioLibra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioPrio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 24)); // NOI18N
        jLabel1.setText("Registre las Rutas de Envio.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 400, 40);

        jLabel2.setText("Destino:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 90, 15);

        jLabel3.setText("Nombre Ruta:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 100, 15);
        jPanel1.add(txtDestino);
        txtDestino.setBounds(30, 190, 260, 32);
        jPanel1.add(txtNombreR);
        txtNombreR.setBounds(30, 110, 260, 32);

        jLabel5.setText("Estado de la Ruta:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 140, 15);

        cmbEstadoRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(cmbEstadoRuta);
        cmbEstadoRuta.setBounds(30, 270, 102, 32);

        btnCrearRuta.setText("Crear Ruta");
        btnCrearRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRutaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearRuta);
        btnCrearRuta.setBounds(170, 360, 190, 80);

        jLabel4.setText("Precio del Destino:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 90, 130, 15);
        jPanel1.add(txtPrecioDestino);
        txtPrecioDestino.setBounds(350, 110, 110, 32);
        jPanel1.add(txtPrecioLibra);
        txtPrecioLibra.setBounds(350, 190, 110, 32);

        jLabel6.setText("Precio x Libra:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 170, 120, 15);

        jLabel7.setText("Precio de Priorizacion:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 250, 150, 15);
        jPanel1.add(txtPrecioPrio);
        txtPrecioPrio.setBounds(350, 270, 110, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRutaActionPerformed
        crearRuta();
    }//GEN-LAST:event_btnCrearRutaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRuta;
    private javax.swing.JComboBox<String> cmbEstadoRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNombreR;
    private javax.swing.JTextField txtPrecioDestino;
    private javax.swing.JTextField txtPrecioLibra;
    private javax.swing.JTextField txtPrecioPrio;
    // End of variables declaration//GEN-END:variables

    public void crearRuta() {
        String nombre, destino, cmbEstado = "";
        int cmb_Estado, validacion = 0, precioPriorizacion;
        float precioDestino, precioLibra;
        nombre = txtNombreR.getText().trim();
        destino = txtDestino.getText().trim();
        cmb_Estado = cmbEstadoRuta.getSelectedIndex() + 1;
        precioDestino = Float.parseFloat(txtPrecioDestino.getText().trim());
        precioLibra = Float.parseFloat(txtPrecioLibra.getText().trim());
        precioPriorizacion = Integer.parseInt(txtPrecioPrio.getText().trim());
        if (nombre.equals("")) {
            txtNombreR.setBackground(Color.red);
            validacion++;
        }
        if (destino.equals("")) {
            txtDestino.setBackground(Color.red);
            validacion++;
        }
        if (cmb_Estado == 1) {
            cmbEstado = "Activo";
        } else if (cmb_Estado == 2) {
            cmbEstado = "Inactivo";
        }
        try {
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT nombre_ruta FROM Rutas WHERE nombre_ruta='"
                    + nombre + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtNombreR.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Ruta ya existe! \n Crea otra ruta");
                cn.close();
            } else {
                cn.close();
                if (validacion == 0) {
                    try {
                        Connection cn1 = ConectorDB.conexion();
                        PreparedStatement ps1 = cn1.prepareStatement("INSERT INTO Rutas VALUES(?,?,?,?,?,?,?)");
                        ps1.setInt(1, 0);
                        ps1.setString(2, nombre);
                        ps1.setString(3, cmbEstado);
                        ps1.setString(4, destino);
                        ps1.setFloat(5, precioLibra);
                        ps1.setFloat(6, precioDestino);
                        ps1.setInt(7, precioPriorizacion);
                        ps1.executeUpdate();
                        cn1.close();
                        clear();
                        txtNombreR.setBackground(Color.green);
                        txtDestino.setBackground(Color.green);
                        txtPrecioDestino.setBackground(Color.green);
                        txtPrecioLibra.setBackground(Color.green);
                        txtPrecioPrio.setBackground(Color.green);
                        JOptionPane.showMessageDialog(null, "Ruta creada exitosamente!");
                        this.dispose();
                    } catch (SQLException e) {
                        System.err.println("Error al crear ruta." + e);
                        JOptionPane.showMessageDialog(null, "Error al crear ruta!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Campos incompletos!! \n Ingrese todos los datos.");

                }

            }
        } catch (SQLException e) {
            System.err.println("Error al validar ruta" + e);
            JOptionPane.showMessageDialog(null, "Error al comparar ruta!");
        }
    }

    public void clear() {
        txtNombreR.setText("");
        txtDestino.setText("");
        cmbEstadoRuta.setSelectedIndex(0);
        txtPrecioDestino.setText("");
        txtPrecioLibra.setText("");
        txtPrecioPrio.setText("");
    }

}
