package UI.Administrador;

import java.util.ArrayList;
import javax.swing.WindowConstants;
import Class.ConectorDB;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;

/**
 *
 * @author jara
 */
public class Reporte1 extends javax.swing.JFrame {

    Connection cn = ConectorDB.conexion();

    /**
     * Creates new form Reporte1
     */
    public Reporte1() {
        initComponents();
        setSize(800, 500);
        setResizable(false);
        setTitle("Reporte de Paquetes");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        rutas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        txtNoRuta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbRuta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnVerPaquetes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText(" Paquetes que estan en Ruta:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 150, 210, 15);

        jLabel2.setText("Paquetes que no estan en Ruta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 250, 220, 15);
        jPanel1.add(txtRuta);
        txtRuta.setBounds(410, 150, 90, 32);
        jPanel1.add(txtNoRuta);
        txtNoRuta.setBounds(410, 250, 90, 32);

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        jLabel3.setText("Seleccione la Ruta que desea ver:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 30, 410, 40);

        jPanel1.add(cmbRuta);
        cmbRuta.setBounds(140, 70, 350, 32);

        jButton1.setText("Exportar a HTML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 320, 190, 70);

        btnVerPaquetes.setText("Ver Paquetes");
        btnVerPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPaquetesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerPaquetes);
        btnVerPaquetes.setBounds(530, 70, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-5, 2, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearHTML();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPaquetesActionPerformed
        paquetesEnRuta();
        paquetesFueraRuta();
    }//GEN-LAST:event_btnVerPaquetesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerPaquetes;
    private javax.swing.JComboBox<String> cmbRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNoRuta;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
 //Busca las rutas que existan y las muestra para que//el nuevo punto de control sea asignado a uno de estos
    public void rutas() {
        ArrayList<String> list = new ArrayList<String>();
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT nombre_ruta FROM Rutas");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {                                                                       
                list.add(rs.getString("nombre_ruta"));                                                
            }
            for (int i = 0; i < list.size(); i++) {
                cmbRuta.addItem(list.get(i));
            }

        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
    }
//Busca las rutas que existan y las muestra para que //el nuevo punto de control sea asignado a uno de estos
    public void paquetesFueraRuta() {
        String cantRegistros;
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT COUNT(*) as total FROM Paquete WHERE localizacion=destino AND ruta='" + cmbRuta.getSelectedItem().toString() + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {                                                                        
                cantRegistros = rs.getString("total");                                                
                txtNoRuta.setText(cantRegistros);
            }
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
    }
//Busca las rutas que existan y las muestra para que el nuevo punto de control sea asignado a uno de estos
    public void paquetesEnRuta() {
        String cantRegistros;
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT COUNT(*) as total FROM Paquete WHERE localizacion<>destino AND ruta='" + cmbRuta.getSelectedItem().toString() + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {                                                                        
                cantRegistros = rs.getString("total");                                                
                txtRuta.setText(cantRegistros);
            }
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
    }

    private void crearHTML() {
        String tx1 = jLabel1.getText();
        String tx2 = jLabel2.getText();
        String enRuta = txtRuta.getText();
        String fueraRuta = txtNoRuta.getText();

        FileWriter filewriter = null;
        PrintWriter printw = null;

        try {
            filewriter = new FileWriter("/home/jara/Desktop/IPC2_Proyect1/IPC2_Proyect1/HTML/" + cmbRuta.getSelectedItem().toString() + ".html");
            printw = new PrintWriter(filewriter);

            printw.println("<html>");
            printw.println("<head><title>Reporte 1 Paquetes</title></head>");
            printw.println("<body bgcolor=\"#99CC99\">");

            printw.println("<center><h1><font color=\"navy\">" + tx1 + " " + enRuta + "</font></h1></center>");
            printw.println("<center><h1><font color=\"navy\">" + tx2 + " " + fueraRuta + "</font></h1></center>");

            printw.println("</body>");
            printw.println("</html>");

            printw.close();

            System.out.println("HTML creado con exito");
        } catch (IOException e) {
            System.err.println("Erro al crear HTML " + e);
        }

    }
}
