package UI.Administrador;

import Class.ConectorDB;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jara
 */
public class Reportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reportes
     */
    DefaultTableModel model = new DefaultTableModel();
    Connection cn = ConectorDB.conexion();

    public Reportes() {
        initComponents();
        setSize(800, 500);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane.setViewportView(table);

        getContentPane().add(ScrollPane);
        ScrollPane.setBounds(20, 40, 750, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    public void tablePaquetesEnRuta() {

    }

    public void tableGanancias() {
        try {
            PreparedStatement ps = cn.prepareStatement(
                    "SELECT ruta, costo, precio, ganancias FROM Paquete");
            ResultSet rs = ps.executeQuery();
            table = new JTable(model);
            ScrollPane.setViewportView(table);
            model.addColumn("Ruta");
            model.addColumn("Costo");
            model.addColumn("Ingreso");
            model.addColumn("Ganancias");
            while (rs.next()) {
                Object[] ob = new Object[6];
                for (int i = 0; i < ob.length; i++) {
                    ob[i] = rs.getObject(i + 1);
                }
                model.addRow(ob);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al rellenar la tabla");
            JOptionPane.showMessageDialog(null, "Error en la conexion DB con la Tabla");
        }
    }

    public void tableClientes() {
    }

    public void tablePopularidad() {
    }
}
