package UI.Operador;

import UI.Inicio.FromPrincipal;

/**
 *
 * @author jara
 */
public class Operador extends javax.swing.JFrame {

    /**
     * Creates new form Operador
     */
    public Operador() {
        initComponents();
        setSize(650, 500);
        setResizable(false);
        setTitle("Operador");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProcesarPA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(129, 216, 37));
        jPanel1.setLayout(null);

        btnProcesarPA.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnProcesarPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnProcesarPA.setText("Procesar Paquete");
        btnProcesarPA.setBorder(null);
        btnProcesarPA.setContentAreaFilled(false);
        btnProcesarPA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcesarPA.setPreferredSize(new java.awt.Dimension(120, 100));
        btnProcesarPA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProcesarPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarPAActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcesarPA);
        btnProcesarPA.setBounds(60, 100, 200, 130);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 20, 420, 40);

        jButton1.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apoyo-tecnico.png"))); // NOI18N
        jButton1.setText("Modificar Tarifa");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 90, 190, 120);

        btnSalir.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(480, 360, 120, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarPAActionPerformed
        jFProcesarPaquete procesar = new jFProcesarPaquete();
        procesar.setVisible(true);
    }//GEN-LAST:event_btnProcesarPAActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        FromPrincipal f = new FromPrincipal();
        f.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesarPA;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
